/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "loc_api_cb.h"

bool_t
xdr_rpc_loc_event_cb_f_type_args (XDR *xdrs, rpc_loc_event_cb_f_type_args *objp)
{
	register int32_t *buf;

	 if (!xdr_rpc_uint32 (xdrs, &objp->cb_id))
		 return FALSE;
	 if (!xdr_rpc_loc_client_handle_type (xdrs, &objp->loc_handle))
		 return FALSE;
	 if (!xdr_rpc_loc_event_mask_type (xdrs, &objp->loc_event))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->loc_event_payload, sizeof (rpc_loc_event_payload_u_type), (xdrproc_t) xdr_rpc_loc_event_payload_u_type))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_loc_event_cb_f_type_rets (XDR *xdrs, rpc_loc_event_cb_f_type_rets *objp)
{
	register int32_t *buf;

	 if (!xdr_rpc_int32 (xdrs, &objp->loc_event_cb_f_type_result))
		 return FALSE;
	return TRUE;
}
